module.exports = {
	DISCORD_DOMAIN: 'discord.com',
	API_VERSION: 9,
	GATEWAY: 'wss://gateway.discord.gg?encoding=json&v=9',
	COMPONENT_TYPES: {
	    ACTION_ROW: 1,
	    BUTTON: 2,
	    SELECT_MENU: 3
	},
	BUTTON_STYLES: {
	    PRIMARY: 1,
	    SECONDARY: 2,
	    SUCCESS: 3,
	    DANGER: 4,
	    LINK: 5
	},
	INTENTS: {
		GUILDS: 1 << 0,
		GUILD_MEMBERS: 1 << 1,
		GUILD_BANS: 1 << 2,
		GUILD_EMOJIS_AND_STICKERS: 1 << 3,
		GUILD_INTEGRATIONS: 1 << 4,
		GUILD_WEBHOOKS: 1 << 5,
		GUILD_INVITES: 1 << 6,
		GUILD_VOICE_STATES: 1 << 7,
		GUILD_PRESENCES: 1 << 8,
		GUILD_MESSAGES: 1 << 9,
		GUILD_MESSAGE_REACTIONS: 1 << 10,
		GUILD_MESSAGE_TYPING: 1 << 11,
		DIRECT_MESSAGES: 1 << 12,
		DIRECT_MESSAGE_REACTIONS: 1 << 13,
		DIRECT_MESSAGE_TYPING: 1 << 14
	}
}